'use strict';
const cp=require('child_process'),fs=require('fs'),os=require('os'),path=require('path');
const ROOT=path.join(process.env.LOCALAPPDATA||path.join(os.homedir(),'AppData','Local'),'WrdUtilities','InterpEngine');
const STATE=path.join(ROOT,'install-state.json'),PY=path.join(ROOT,'python','python.exe'),RUN=path.join(ROOT,'engine','run_gmfss.py');
function state(){try{return JSON.parse(fs.readFileSync(STATE,'utf8').replace(/^\uFEFF/,''))}catch(_){return null}}
function getStatus(){const s=state();return{ready:!!(s&&s.status==='ready'&&fs.existsSync(PY)&&fs.existsSync(RUN)),version:s&&s.version,installRoot:ROOT,state:s}}
function installEngine({manifestUrl,installerPath,onProgress=()=>{},force=false}){return new Promise((resolve,reject)=>{const a=['-NoProfile','-ExecutionPolicy','Bypass','-File',installerPath,'-ManifestUrl',manifestUrl,'-InstallRoot',ROOT];if(force)a.push('-Force');const p=cp.spawn('powershell.exe',a,{windowsHide:true});let b='',e='';p.stdout.setEncoding('utf8');p.stdout.on('data',c=>{b+=c;const lines=b.split(/\r?\n/);b=lines.pop()||'';for(const l of lines){if(l.startsWith('WRD_PROGRESS ')){try{onProgress(JSON.parse(l.slice(13)))}catch(_){}}else if(l.trim())onProgress({stage:'log',percent:null,message:l.trim()})}});p.stderr.setEncoding('utf8');p.stderr.on('data',c=>{e+=c;onProgress({stage:'log',percent:null,message:c.trim()})});p.on('error',reject);p.on('close',code=>code===0?resolve(getStatus()):reject(new Error(`Instalação falhou (${code}). ${e}`)))})}
function interpolate({input,output,factor=2,scale=1.0,precision='fp16',onLog=()=>{}}){if(!getStatus().ready)return Promise.reject(new Error('Motor não instalado.'));const a=[RUN,path.resolve(input),'--factor',String(factor),'--scale',String(scale),'--precision',precision];if(output)a.push('--output',path.resolve(output));return new Promise((resolve,reject)=>{const p=cp.spawn(PY,a,{cwd:ROOT,windowsHide:true});let e='';p.stdout.on('data',c=>onLog(c.toString()));p.stderr.on('data',c=>{e+=c;onLog(c.toString())});p.on('error',reject);p.on('close',code=>code===0?resolve({code}):reject(new Error(`Interpolação falhou (${code}). ${e}`)))})}
module.exports={INSTALL_ROOT:ROOT,getStatus,installEngine,interpolate};
